import { describe, expect, it } from "vitest";
import {
  getPullRequestRuntimeContext,
  normalizeGitHubAuthorType,
  normalizeLabels
} from "../../src/action/context.js";

const repo = {
  owner: "agentguard",
  repo: "agentguard-action"
};

describe("GitHub pull request context", () => {
  it("returns null for non-PR events", () => {
    expect(
      getPullRequestRuntimeContext({
        eventName: "push",
        repo,
        payload: {}
      })
    ).toBeNull();
  });

  it("converts pull_request payload metadata into runtime context", () => {
    const context = getPullRequestRuntimeContext({
      eventName: "pull_request",
      repo,
      payload: {
        repository: {
          name: "repo-from-payload",
          owner: {
            login: "owner-from-payload"
          }
        },
        pull_request: {
          number: 42,
          title: "AI generated implementation update",
          body: "Generated by an agent.",
          head: {
            ref: "copilot/update-auth"
          },
          user: {
            login: "github-copilot[bot]",
            type: "Bot"
          },
          labels: [{ name: "agent-pr" }, { name: "risk-review" }]
        }
      }
    });

    expect(context).toEqual({
      owner: "owner-from-payload",
      repo: "repo-from-payload",
      pullNumber: 42,
      authorLogin: "github-copilot[bot]",
      authorType: "bot",
      branchName: "copilot/update-auth",
      title: "AI generated implementation update",
      body: "Generated by an agent.",
      labels: ["agent-pr", "risk-review"]
    });
  });

  it("falls back safely when optional PR metadata is missing", () => {
    const context = getPullRequestRuntimeContext({
      eventName: "pull_request",
      repo,
      payload: {
        pull_request: {
          number: 7
        }
      }
    });

    expect(context).toEqual({
      owner: "agentguard",
      repo: "agentguard-action",
      pullNumber: 7,
      authorLogin: "unknown",
      authorType: "unknown",
      branchName: "",
      title: "",
      body: "",
      labels: []
    });
  });

  it("normalizes author types", () => {
    expect(normalizeGitHubAuthorType("Bot")).toBe("bot");
    expect(normalizeGitHubAuthorType("User")).toBe("user");
    expect(normalizeGitHubAuthorType("Organization")).toBe("unknown");
    expect(normalizeGitHubAuthorType(undefined)).toBe("unknown");
  });

  it("normalizes string and object labels", () => {
    expect(normalizeLabels(["agent-pr", { name: "copilot" }, { name: " " }])).toEqual([
      "agent-pr",
      "copilot"
    ]);
  });
});
