import type { AgentGuardConfig } from './types.js';

export const DEFAULT_CONFIG: AgentGuardConfig = {
  enabled: true,
  mode: 'ai-only',
  commentThreshold: 'high',

  agentAuthors: [
    'github-copilot[bot]',
    'cursor-agent',
    'devin-ai',
    'codex-agent',
    'claude-code'
  ],

  aiLabels: ['ai-generated', 'agent-pr', 'bot', 'cursor', 'copilot', 'codex', 'claude-code', 'devin'],

  criticalPaths: [
    'auth/**',
    'oauth/**',
    'identity/**',
    'iam/**',
    'rbac/**',
    'billing/**',
    'payments/**',
    'permissions/**',
    'security/**',
    'crypto/**',
    'infra/**',
    'terraform/**',
    'k8s/**',
    'migrations/**',
    '.github/workflows/**'
  ],

  dependencyFiles: [
    'package.json',
    'pnpm-lock.yaml',
    'pnpm-workspace.yaml',
    'yarn.lock',
    'package-lock.json',
    'npm-shrinkwrap.json',
    'bun.lock',
    'bun.lockb',
    'deno.json',
    'deno.jsonc',
    'deno.lock',
    'requirements.txt',
    'requirements*.txt',
    'pyproject.toml',
    'poetry.lock',
    'Pipfile',
    'Pipfile.lock',
    'setup.py',
    'setup.cfg',
    'uv.lock',
    'go.mod',
    'go.sum',
    'go.work',
    'go.work.sum',
    'Cargo.toml',
    'Cargo.lock',
    'Gemfile',
    'Gemfile.lock',
    'gems.rb',
    'gems.locked',
    'pom.xml',
    'build.gradle',
    'build.gradle.kts',
    'settings.gradle',
    'settings.gradle.kts',
    'gradle.lockfile',
    'gradle/libs.versions.toml',
    'composer.json',
    'composer.lock',
    '*.csproj',
    '*.fsproj',
    '*.vbproj',
    '*.sln',
    'packages.config',
    'packages.lock.json',
    'Directory.Packages.props',
    'NuGet.config',
    'global.json',
    '.terraform.lock.hcl'
  ],

  migrationFiles: [
    'migrations/**',
    'db/migrate/**',
    'db/migrations/**',
    'database/migrations/**',
    'supabase/migrations/**',
    'src/main/resources/db/migration/**',
    'liquibase/**',
    'schema.prisma',
    'db/schema.rb',
    '*.sql',
    'graphql.schema',
    '*.graphql',
    'openapi.yaml',
    'openapi.yml',
    'openapi.json',
    'swagger.yaml',
    'swagger.yml',
    'swagger.json',
    '*.proto'
  ],

  ciCdFiles: [
    '.github/workflows/**',
    '.github/actions/**',
    '.gitlab-ci.yml',
    '.circleci/**',
    '.buildkite/**',
    'Jenkinsfile',
    'azure-pipelines.yml',
    'azure-pipelines.yaml',
    'cloudbuild.yml',
    'cloudbuild.yaml',
    'Dockerfile',
    'Dockerfile.*',
    '.dockerignore',
    'docker-compose.yml',
    'docker-compose.yaml',
    'docker-compose.*.yml',
    'docker-compose.*.yaml',
    'compose.yml',
    'compose.yaml',
    'deploy/**',
    'deployment/**',
    'infra/**',
    'terraform/**',
    '*.tf',
    '*.tfvars',
    'k8s/**',
    'kubernetes/**',
    'helm/**',
    'charts/**',
    'helmfile.yaml',
    'helmfile.yml',
    'skaffold.yaml',
    'skaffold.yml',
    'kustomization.yaml',
    'kustomization.yml'
  ],

  secretsFiles: [
    '.env',
    '.env.*',
    '.envrc',
    '.npmrc',
    '.pypirc',
    '.netrc',
    '*.pem',
    '*.key',
    '*.crt',
    '*.p12',
    '*.pfx',
    '*.jks',
    '*.keystore',
    '*.tfstate',
    '*.tfstate.backup',
    'id_rsa',
    'id_dsa',
    'id_ecdsa',
    'id_ed25519',
    '.ssh/**',
    '.aws/credentials',
    'secrets/**',
    'config/secrets/**',
    'credentials/**',
    'kubeconfig',
    'kubeconfig*',
    '*kubeconfig*',
    'service-account*.json',
    '*service-account*.json'
  ],

  ignorePaths: [
    'docs/**',
    '*.md',
    'generated/**',
    'dist/**',
    'build/**',
    'coverage/**',
    'node_modules/**',
    'vendor/**',
    '.next/**',
    '.nuxt/**',
    'out/**',
    'target/**',
    'tmp/**',
    '.cache/**',
    '.terraform/**'
  ],

  sourceFilePatterns: [
    'src/**',
    'app/**',
    'lib/**',
    'packages/**',
    '*.ts',
    '*.tsx',
    '*.js',
    '*.jsx',
    '*.mjs',
    '*.cjs',
    '*.py',
    '*.pyi',
    '*.go',
    '*.rs',
    '*.rb',
    '*.rake',
    'Rakefile',
    'src/main/**',
    '*.java',
    '*.kt',
    '*.kts',
    '*.php',
    '*.cs',
    '*.csx',
    '*.fs',
    '*.vb'
  ],

  testFilePatterns: [
    '*.test.ts',
    '*.test.tsx',
    '*.spec.ts',
    '*.spec.tsx',
    '*.test.js',
    '*.spec.js',
    '*.test.jsx',
    '*.spec.jsx',
    '*.test.mjs',
    '*.spec.mjs',
    '*.test.cjs',
    '*.spec.cjs',
    '__tests__/**',
    'tests/**',
    'test_*.py',
    '*_test.py',
    'conftest.py',
    '*_test.go',
    '*_test.rs',
    'spec/**',
    'test/**',
    '*_spec.rb',
    'src/test/**',
    '*Test.java',
    '*Tests.java',
    '*IT.java',
    '*Test.kt',
    '*Tests.kt',
    '*IT.kt',
    '*Test.php',
    '*Tests.cs',
    '*Test.cs',
    '*.Tests/**',
    'cypress/**',
    'e2e/**'
  ],

  largePr: {
    largeFileCount: 30,
    largeLineCount: 800,
    maxChangedFilesAnalyzed: 300
  }
};

export function resolveAgentGuardConfig(config?: Partial<AgentGuardConfig>): AgentGuardConfig {
  return {
    ...DEFAULT_CONFIG,
    ...config,
    largePr: {
      ...DEFAULT_CONFIG.largePr,
      ...(config?.largePr ?? {})
    }
  };
}
