import type { AgentGuardConfig, RiskInput, RiskSignal } from "../types.js";

const AI_PHRASE_MARKERS = [
  "ai generated",
  "generated by ai",
  "agent generated",
  "agent pr",
  "copilot",
  "cursor",
  "codex",
  "claude code",
  "devin"
];

const AI_TOKEN_MARKERS = new Set(["ai", "agent"]);

type AnalysisDecision =
  | {
      shouldAnalyze: true;
    }
  | {
      shouldAnalyze: false;
      skipReason: string;
    };

function normalize(value: string): string {
  return value.trim().toLowerCase();
}

function normalizeForMarkerMatching(value: string): string {
  return normalize(value)
    .replace(/\[[^\]]+\]/g, " ")
    .replace(/[^a-z0-9]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function tokens(value: string): Set<string> {
  const normalized = normalizeForMarkerMatching(value);

  if (normalized.length === 0) {
    return new Set();
  }

  return new Set(normalized.split(" "));
}

function includesAnyMarker(value: string): boolean {
  const normalized = normalizeForMarkerMatching(value);

  if (normalized.length === 0) {
    return false;
  }

  if (AI_PHRASE_MARKERS.some((marker) => normalized.includes(marker))) {
    return true;
  }

  const valueTokens = tokens(value);

  return [...AI_TOKEN_MARKERS].some((marker) => valueTokens.has(marker));
}

export function hasAiLabel(labels: string[], config: AgentGuardConfig): boolean {
  const configuredLabels = new Set(config.aiLabels.map(normalize));

  return labels.some((label) => configuredLabels.has(normalize(label)) || includesAnyMarker(label));
}

export function isConfiguredAgentAuthor(authorLogin: string, config: AgentGuardConfig): boolean {
  const normalizedAuthor = normalize(authorLogin);

  return config.agentAuthors.some((agentAuthor) => normalize(agentAuthor) === normalizedAuthor);
}

export function isAiAuthored(input: RiskInput): boolean {
  const authorLogin = normalize(input.authorLogin);

  return (
    input.authorType === "bot" ||
    authorLogin.endsWith("[bot]") ||
    tokens(authorLogin).has("bot") ||
    isConfiguredAgentAuthor(input.authorLogin, input.config) ||
    includesAnyMarker(input.authorLogin) ||
    hasAiLabel(input.labels, input.config) ||
    includesAnyMarker(input.branchName) ||
    includesAnyMarker(input.title) ||
    includesAnyMarker(input.body)
  );
}

export function shouldAnalyzeInput(input: RiskInput): AnalysisDecision {
  if (!input.config.enabled) {
    return { shouldAnalyze: false, skipReason: "AgentGuard is disabled by configuration." };
  }

  if (input.config.mode === "all-prs") {
    return { shouldAnalyze: true };
  }

  if (input.config.mode === "labeled") {
    return hasAiLabel(input.labels, input.config)
      ? { shouldAnalyze: true }
      : { shouldAnalyze: false, skipReason: "PR does not have an AgentGuard AI/bot label." };
  }

  return isAiAuthored(input)
    ? { shouldAnalyze: true }
    : { shouldAnalyze: false, skipReason: "PR does not appear to be AI/bot-authored." };
}

export function aiAuthorRule(input: RiskInput): RiskSignal | null {
  if (!isAiAuthored(input)) {
    return null;
  }

  return {
    id: "ai_author",
    label: "AI/bot authorship detected",
    severity: "low",
    description: "PR appears to be AI/bot-authored based on author, labels, branch, title, or body."
  };
}
